In [ ]:
import pandas as pd

In [ ]:
data_set = pd.read_csv("cancellation prediction.csv")
df = pd.DataFrame(data_set)
df.head()

,lead_time,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,reserved_room_type,deposit_type,is_canceled
0,6,2015,July,1,0,2,1,0.0,0,HB,PRT,Offline TA/TO,TA/TO,0,A,No Deposit,0
1,88,2015,July,1,0,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,A,No Deposit,1
2,65,2015,July,1,0,4,1,0.0,0,BB,PRT,Online TA,TA/TO,0,A,No Deposit,1
3,92,2015,July,1,2,4,2,0.0,0,BB,PRT,Online TA,TA/TO,0,A,No Deposit,1
4,100,2015,July,2,0,2,2,0.0,0,BB,PRT,Online TA,TA/TO,0,A,No Deposit,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9779 entries, 0 to 9778
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   lead_time                  9779 non-null   int64
 1   arrival_date_year          9779 non-null   int64
 2   arrival_date_month         9779 non-null   object
 3   arrival_date_day_of_month  9779 non-null   int64
 4   stays_in_weekend_nights    9779 non-null   int64
 5   stays_in_week_nights       9779 non-null   int64
 6   adults                     9779 non-null   int64
 7   children                   9775 non-null   float64
 8   babies                     9779 non-null   int64
 9   meal                       9779 non-null   object
 10  country                    9765 non-null   object
 11  market_segment             9779 non-null   object
 12  distribution_channel       9779 non-null   object
 13  is_repeated_guest          9779 non-null   int64
 14  reserved_room_type         9779 non-null   object
 15  deposit_type               9779 non-null   object
 16  is_canceled                9779 non-null   int64
dtypes: float64(1), int64(9), object(7)
memory usage: 1.3+ MB

In [ ]:
x = df.drop(["is_canceled","lead_time"], axis=1)
y = df["is_canceled"]

In [ ]:
# Encoding data
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
categorical_data = x.select_dtypes(include=["object"]).columns
for column in categorical_data:
    x[column] = encoder.fit_transform(x[column])

In [ ]:
# Scaling data
from sklearn.preprocessing import StandardScaler

scalar = StandardScaler()
for column in x.columns:
    x[column] = scalar.fit_transform(x[[column]])

In [ ]:
x.head()

,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,reserved_room_type,deposit_type
0,-0.733033,0.013319,-1.721241,-0.888925,-0.116286,-1.750830,-0.192111,-0.043473,1.444461,0.771832,0.062328,0.302644,0.0,-0.328161,-0.449709
1,-0.733033,0.013319,-1.721241,-0.888925,1.187794,0.416432,-0.192111,-0.043473,-0.540975,0.771832,1.002931,0.302644,0.0,-0.328161,-0.449709
2,-0.733033,0.013319,-1.721241,-0.888925,1.187794,-1.750830,-0.192111,-0.043473,-0.540975,0.771832,1.002931,0.302644,0.0,-0.328161,-0.449709
3,-0.733033,0.013319,-1.721241,1.259567,1.187794,0.416432,-0.192111,-0.043473,-0.540975,0.771832,1.002931,0.302644,0.0,-0.328161,-0.449709
4,-0.733033,0.013319,-1.603996,-0.888925,-0.116286,0.416432,-0.192111,-0.043473,-0.540975,0.771832,1.002931,0.302644,0.0,-0.328161,-0.449709

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8829243353783232

In [ ]:
pip install pickle

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle

In [ ]:
import pickle
pickle.dump(model, open("model.pkl", "wb"))