In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(pd.read_csv('hotel_bookings.csv'))

In [ ]:
df.isna().sum()

index                                  0
hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [ ]:
df.DESCR

,index,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
119385,119385,City Hotel,0,23,2017,August,35,30,2,5,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,06-09-17
119386,119386,City Hotel,0,102,2017,August,35,31,2,5,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,07-09-17
119387,119387,City Hotel,0,34,2017,August,35,31,2,5,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,07-09-17
119388,119388,City Hotel,0,109,2017,August,35,31,2,5,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,07-09-17
119389,119389,City Hotel,0,205,2017,August,35,29,2,7,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,07-09-17

In [ ]:
df.drop(df[df['hotel'] == 'Resort Hotel'].index, inplace=True)

In [ ]:
df.isna().sum()

index                                 0
hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              4
babies                                0
meal                                  0
country                              24
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                              8131
company                           75641
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
dtype: int64

In [ ]:
df = df[['index','arrival_date_year','arrival_date_month','arrival_date_day_of_month','adults','babies','children']]

In [ ]:
countries = df['country'].unique()
print(countries)

['PRT' 'ITA' 'ESP' 'DEU' 'FRA' 'NLD' 'GBR' 'ROU' 'BRA' 'SWE' 'AUT' 'AGO'
 'BEL' 'CHE' 'NOR' 'RUS' 'ISR' 'IRL' 'POL' 'CHN' 'USA' 'MAR' 'AUS' 'MOZ'
 'TUN' 'DNK' 'MEX' 'GRC' 'DZA' 'COL' 'LUX' 'CN' 'LVA' 'FIN' 'HRV' 'STP'
 'BGR' 'UKR' 'VEN' 'TWN' 'IRN' 'KOR' 'TUR' 'BLR' 'JPN' 'CZE' 'HUN' 'AZE'
 'KAZ' 'IND' 'NZL' 'IDN' 'LTU' 'LBN' 'SRB' 'SVN' 'SVK' 'MYS' 'CMR' 'CHL'
 'ARG' nan 'SGP' 'SEN' 'PER' 'EGY' 'SAU' 'KNA' 'JOR' 'ZAF' 'THA' 'KWT'
 'LKA' 'ALB' 'ETH' 'PHL' 'ARE' 'ECU' 'OMN' 'IRQ' 'AND' 'CPV' 'MUS' 'HND'
 'NGA' 'RWA' 'EST' 'PAK' 'GEO' 'GIB' 'ZMB' 'QAT' 'KHM' 'HKG' 'MCO' 'BGD'
 'ISL' 'UZB' 'URY' 'IMN' 'TJK' 'ARM' 'MDV' 'NIC' 'GGY' 'BEN' 'MAC' 'CYP'
 'VGB' 'MLT' 'CRI' 'TZA' 'JEY' 'GAB' 'MKD' 'BIH' 'VNM' 'GHA' 'TMP' 'GLP'
 'KEN' 'PRI' 'DOM' 'LIE' 'GNB' 'BHR' 'MNE' 'UMI' 'MYT' 'FRO' 'CIV' 'ZWE'
 'MMR' 'PAN' 'BFA' 'LBY' 'MLI' 'NAM' 'BOL' 'JAM' 'SYC' 'PRY' 'BRB' 'ABW'
 'AIA' 'SLV' 'DMA' 'CUB' 'PYF' 'UGA' 'GUY' 'LCA' 'ATA' 'GTM' 'ASM' 'SYR'
 'TGO' 'SUR' 'MRT' 'CAF' 'NCL' 'KIR' 'SDN' 'ATF' 'SLE' 'LAO' 'COM']

In [ ]:
df.head()

,index,arrival_date_year,arrival_date_month,arrival_date_day_of_month,adults,babies,children
40060,40060,2015,July,1,1,0,0.0
40061,40061,2015,July,1,2,0,0.0
40062,40062,2015,July,1,1,0,0.0
40063,40063,2015,July,1,2,0,0.0
40064,40064,2015,July,2,2,0,0.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79330 entries, 40060 to 119389
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   index                      79330 non-null  int64
 1   arrival_date_year          79330 non-null  int64
 2   arrival_date_month         79330 non-null  object
 3   arrival_date_day_of_month  79330 non-null  int64
 4   adults                     79330 non-null  int64
 5   babies                     79330 non-null  int64
 6   children                   79326 non-null  float64
dtypes: float64(1), int64(5), object(1)
memory usage: 4.2+ MB

In [ ]:
# Replace NaN values in 'children' column with 0 before converting to integer
df['total_visitors'] = df['adults'] + df['babies'] + df['children'].fillna(0).astype(int)

In [ ]:
df.head()

,index,arrival_date_year,arrival_date_month,arrival_date_day_of_month,adults,babies,children,total_visitors
40060,40060,2015,July,1,1,0,0.0,1
40061,40061,2015,July,1,2,0,0.0,2
40062,40062,2015,July,1,1,0,0.0,1
40063,40063,2015,July,1,2,0,0.0,2
40064,40064,2015,July,2,2,0,0.0,2

In [ ]:
months = df['arrival_date_month'].unique()
print(months)

['July' 'August' 'September' 'October' 'November' 'December' 'January'
 'February' 'March' 'April' 'May' 'June']

In [ ]:
df.head()

,index,arrival_date_year,arrival_date_month,arrival_date_day_of_month,adults,babies,children,total_visitors
40060,40060,2015,5,1,1,0,0.0,1
40061,40061,2015,5,1,2,0,0.0,2
40062,40062,2015,5,1,1,0,0.0,1
40063,40063,2015,5,1,2,0,0.0,2
40064,40064,2015,5,2,2,0,0.0,2

In [ ]:
import pandas as pd

# Assuming your DataFrame is named 'df' and has a column 'arrival_date_month' with month names

# Create a dictionary mapping month names to month numbers
month_mapping = {
    'January': 1,
    'February': 2,
    'March': 3,
    'April': 4,
    'May': 5,
    'June': 6,
    'July': 7,
    'August': 8,
    'September': 9,
    'October': 10,
    'November': 11,
    'December': 12
}

# Use the map function to apply the mapping to the 'arrival_date_month' column
df['arrival_date_month_num'] = df['arrival_date_month'].map(month_mapping)

In [ ]:
df.head()

,index,arrival_date_year,arrival_date_month,arrival_date_day_of_month,adults,babies,children,total_visitors,arrival_date_month_num
40060,40060,2015,July,1,1.0,0.0,0.0,1.0,7
40061,40061,2015,July,1,2.0,0.0,0.0,2.0,7
40062,40062,2015,July,1,1.0,0.0,0.0,1.0,7
40063,40063,2015,July,1,2.0,0.0,0.0,2.0,7
40064,40064,2015,July,2,2.0,0.0,0.0,2.0,7

In [ ]:
df.drop(['arrival_date_month'], axis=1, inplace=True)

In [ ]:
df.head()

,index,arrival_date_year,arrival_date_day_of_month,adults,babies,children,total_visitors,arrival_date_month_num
40060,40060,2015,1,1,0,0.0,1,7
40061,40061,2015,1,2,0,0.0,2,7
40062,40062,2015,1,1,0,0.0,1,7
40063,40063,2015,1,2,0,0.0,2,7
40064,40064,2015,2,2,0,0.0,2,7

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79330 entries, 40060 to 119389
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   index                      79330 non-null  int64
 1   arrival_date_year          79330 non-null  int64
 2   arrival_date_day_of_month  79330 non-null  int64
 3   adults                     79330 non-null  int64
 4   babies                     79330 non-null  int64
 5   children                   79326 non-null  float64
 6   total_visitors             79330 non-null  int64
 7   arrival_date_month_num     79330 non-null  int64
dtypes: float64(1), int64(7)
memory usage: 4.8 MB

In [ ]:
grouped_df = df.groupby(['arrival_date_year', 'arrival_date_month_num', 'arrival_date_day_of_month'])
aggregated_df = grouped_df[['children','babies','adults']].sum().reset_index()

In [ ]:
aggregated_df.head()

,arrival_date_year,arrival_date_month_num,arrival_date_day_of_month,children,babies,adults
0,2015,7,1,0.0,0,143
1,2015,7,2,0.0,0,96
2,2015,7,3,0.0,0,28
3,2015,7,4,0.0,0,72
4,2015,7,5,0.0,0,15

In [ ]:
aggregated_df.tail()

,arrival_date_year,arrival_date_month_num,arrival_date_day_of_month,total_visitors
438,2016,9,15,278.0
439,2016,9,16,189.0
440,2016,9,17,55.0
441,2016,9,18,64.0
442,2016,9,19,68.0

In [ ]:
aggregated_df['date'] = pd.to_datetime(aggregated_df[['arrival_date_year', 'arrival_date_month_num', 'arrival_date_day_of_month']].rename(columns={
    'arrival_date_year': 'year',
    'arrival_date_month_num': 'month',
    'arrival_date_day_of_month': 'day'
}), errors='coerce')
aggregated_df = aggregated_df.dropna(subset=['date'])

In [ ]:
aggregated_df.head()

,arrival_date_year,arrival_date_month_num,arrival_date_day_of_month,total_visitors,date
0,2015,7,1,143,2015-07-01
1,2015,7,2,96,2015-07-02
2,2015,7,3,28,2015-07-03
3,2015,7,4,72,2015-07-04
4,2015,7,5,15,2015-07-05

In [ ]:
train_data = aggregated_df[(aggregated_df['date'] >= '2015-07-01') & (aggregated_df['date'] <= '2016-07-01')]
test_data = aggregated_df[(aggregated_df['date'] >= '2016-07-02') & (aggregated_df['date'] <= '2016-07-19')]

In [ ]:
x_train = train_data[['arrival_date_year','arrival_date_month_num','arrival_date_day_of_month']]
y_train = train_data[['children','babies','adults']]
x_test = test_data[['arrival_date_year','arrival_date_month_num','arrival_date_day_of_month']]
y_test = test_data[['children','babies','adults']]

In [ ]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
reg = xgb.XGBRegressor(n_estimators=1000,arly_stopping_rounds=50)
reg.fit(x_train, y_train,
        eval_set=[(x_train, y_train), (x_test, y_test)],
       verbose=False)

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:158: UserWarning: [15:00:04] WARNING: /workspace/src/learner.cc:740:
Parameters: { "arly_stopping_rounds" } are not used.

  warnings.warn(smsg, UserWarning)

XGBRegressor(arly_stopping_rounds=50, base_score=None, booster=None,
             callbacks=None, colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=1000, n_jobs=None,
             num_parallel_tree=None, ...)

In [ ]:
y_pred = reg.predict([[2024,5,11]])

In [ ]:
for i in range(len(y_pred[0])):
    print(int(y_pred[0][i]))

6
0
175

In [ ]:
aggregated_df.to_csv('forecasting_data.csv', index=False)